local area = script.Parent:WaitForChild("TestArea");
local evt = game:GetService("ReplicatedStorage"):WaitForChild("Subtitles");
script.Parent:WaitForChild("ClickDetector").MouseClick:Connect(function()
	evt:FireAllClients(area, {}, {
		{"p", 3, nil, "subtitle test:"};
		{"d", 2};
		{"p", 2, Color3.fromHex("ff0000"), "red!"};
		{"d", 2};
		{"p", 2, Color3.fromHex("00ff00"), "green!"};
		{"d", 2};
		{"p", 2, Color3.fromHex("0000ff"), "blue!"};
		{"d", 2};
		{"p", 8, nil, "really long test subtitles that's so long it needs to wrap the text in order for you to be able to see the entire thing and not have it crop off the subtitle window where you won't be able to see it"};
		{"d", 2};
		{"p", 5, nil, "sorta supports<br/>multiple lines<br/>of text<br/>but this indent is annoying<br/>and now a long delay..."};
		{"d", 8};
		{"p", 3, nil, "lots of subtitles #1"};
		{"p", 3, nil, "lots of subtitles #2"};
		{"p", 3, nil, "lots of subtitles #3"};
		{"p", 3, nil, "lots of subtitles #4"};
		{"p", 3, nil, "lots of subtitles #5"};
		{"p", 3, nil, "lots of subtitles #6"};
		{"p", 3, nil, "lots of subtitles #7"};
		{"p", 3, nil, "lots of subtitles #8"};
		{"p", 3, nil, "lots of subtitles #9"};
		{"p", 3, nil, "lots of subtitles #10"};
		{"p", 3, nil, "lots of subtitles #11"};
		{"p", 3, nil, "lots of subtitles #12"};
		{"p", 3, nil, "lots of subtitles #13"};
		{"p", 3, nil, "lots of subtitles #14"};
		{"p", 3, nil, "lots of subtitles #15"};
		{"p", 3, nil, "lots of subtitles #16"};
		{"p", 3, nil, "lots of subtitles #17"};
		{"p", 3, nil, "lots of subtitles #18"};
		{"p", 3, nil, "lots of subtitles #19"};
		{"p", 3, nil, "lots of subtitles #20"};
		{"p", 3, nil, "lots of subtitles #21"};
		{"p", 3, nil, "lots of subtitles #22"};
		{"p", 3, nil, "lots of subtitles #23"};
		{"p", 3, nil, "lots of subtitles #24"};
		{"p", 3, nil, "lots of subtitles #25"};
		{"p", 3, nil, "lots of subtitles #26"};
		{"p", 3, nil, "lots of subtitles #27"};
		{"p", 3, nil, "lots of subtitles #28"};
		{"p", 3, nil, "lots of subtitles #29"};
		{"p", 3, nil, "lots of subtitles #30"};
		{"p", 3, nil, "lots of subtitles #31"};
		{"p", 3, nil, "lots of subtitles #32"};
		{"p", 3, nil, "lots of subtitles #33"};
		{"p", 3, nil, "lots of subtitles #34"};
		{"p", 3, nil, "lots of subtitles #35"};
		{"p", 3, nil, "lots of subtitles #36"};
		{"p", 3, nil, "lots of subtitles #37"};
		{"p", 3, nil, "lots of subtitles #38"};
		{"p", 3, nil, "lots of subtitles #39"};
		{"p", 3, nil, "lots of subtitles #40"};
		{"p", 3, nil, "lots of subtitles #41"};
		{"p", 3, nil, "lots of subtitles #42"};
		{"p", 3, nil, "lots of subtitles #43"};
		{"p", 3, nil, "lots of subtitles #44"};
		{"p", 3, nil, "lots of subtitles #45"};
		{"p", 3, nil, "lots of subtitles #46"};
		{"p", 3, nil, "lots of subtitles #47"};
		{"p", 3, nil, "lots of subtitles #48"};
		{"p", 3, nil, "lots of subtitles #49"};
		{"p", 3, nil, "lots of subtitles #50"};
		{"p", 3, nil, "lots of subtitles #51"};
		{"p", 3, nil, "lots of subtitles #52"};
		{"p", 3, nil, "lots of subtitles #53"};
		{"p", 3, nil, "lots of subtitles #54"};
		{"p", 3, nil, "lots of subtitles #55"};
		{"p", 3, nil, "lots of subtitles #56"};
		{"p", 3, nil, "lots of subtitles #57"};
		{"p", 3, nil, "lots of subtitles #58"};
		{"p", 3, nil, "lots of subtitles #59"};
		{"p", 3, nil, "lots of subtitles #60"};
		{"p", 3, nil, "lots of subtitles #61"};
		{"p", 3, nil, "lots of subtitles #62"};
		{"p", 3, nil, "lots of subtitles #63"};
		{"p", 3, nil, "lots of subtitles #64"};
		{"p", 3, nil, "lots of subtitles #65"};
		{"p", 3, nil, "lots of subtitles #66"};
		{"p", 3, nil, "lots of subtitles #67"};
		{"p", 3, nil, "lots of subtitles #68"};
		{"p", 3, nil, "lots of subtitles #69"};
		{"p", 3, nil, "lots of subtitles #70"};
		{"p", 3, nil, "lots of subtitles #71"};
		{"p", 3, nil, "lots of subtitles #72"};
		{"p", 3, nil, "lots of subtitles #73"};
		{"p", 3, nil, "lots of subtitles #74"};
		{"p", 3, nil, "lots of subtitles #75"};
		{"p", 3, nil, "lots of subtitles #76"};
		{"p", 3, nil, "lots of subtitles #77"};
		{"p", 3, nil, "lots of subtitles #78"};
		{"p", 3, nil, "lots of subtitles #79"};
		{"p", 3, nil, "lots of subtitles #70"};
		{"p", 3, nil, "lots of subtitles #81"};
		{"p", 3, nil, "lots of subtitles #82"};
		{"p", 3, nil, "lots of subtitles #83"};
		{"p", 3, nil, "lots of subtitles #84"};
		{"p", 3, nil, "lots of subtitles #85"};
		{"p", 3, nil, "lots of subtitles #86"};
		{"p", 3, nil, "lots of subtitles #87"};
		{"p", 3, nil, "lots of subtitles #88"};
		{"p", 3, nil, "lots of subtitles #89"};
		{"p", 3, nil, "lots of subtitles #90"};
		{"p", 3, nil, "lots of subtitles #91"};
		{"p", 3, nil, "lots of subtitles #92"};
		{"p", 3, nil, "lots of subtitles #93"};
		{"p", 3, nil, "lots of subtitles #94"};
		{"p", 3, nil, "lots of subtitles #95"};
		{"p", 3, nil, "lots of subtitles #96"};
		{"p", 3, nil, "lots of subtitles #97"};
		{"p", 3, nil, "lots of subtitles #98"};
		{"p", 3, nil, "lots of subtitles #99"};
		{"p", 3, nil, "lots of subtitles #100"};
		{"d", 3};
		{"p", 4, nil, "i haven't bothered adding a limit on subtitles yet"};
	});
end);
